export const INGREDIENT_ADD = 'ING_A';
export const INGREDIENT_REMOVE = 'ING_R';
export const INGREDIENTS_SET = 'ING_SET';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';


export const PURCHASE_BURGER_START='PURCHASE_ORDER_START';
export const PURCHASE_ORDER_SUCCESS='PURCHASE_ORDER_SUCCESS';
export const PURCHASE_ORDER_FAILED='PURCHASE_ORDER_FAILED';
