export const INGREDIENT_ADD = 'ING_A';
export const INGREDIENT_REMOVE = 'ING_R';
export const INGREDIENTS_SET = 'ING_SET';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';


export const PURCHASE_BURGER_START='PURCHASE_ORDER_START';
export const PURCHASE_BURGER_SUCCESS='PURCHASE_ORDER_SUCCESS';
export const PURCHASE_BURGER_FAIL='PURCHASE_ORDER_FAILED';
export const PURCHASE_INIT='PURCHASE_INIT';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL='FETCH_ORDER_FAIL';